name: nacesta_app
description: " Um projeto em Flutter de uma lista de compras"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.19.5 <4.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  #deve ser usado para implementar imagens 
  assets: 
    - lib/imagens/

